export const SET_LOADING = "SET_LOADING";
export const GET_USER_ACCOUNTS = "GET_USER_ACCOUNTS";
export const GET_AVAILABLE_ACCOUNTS = "GET_AVAILABLE_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
export const SELECT_ALL_ACCOUNTS = "SELECT_ALL_ACCOUNTS";
export const SELECT_ACCOUNT = "SELECT_ACCOUNT";
export const SEND_EMAIL = "SEND_EMAIL";
